language: node_js

node_js: '10'

services:
  - mongodb

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.4-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

after_success: npm run coverage
