language: node_js

node_js: '10'

services:
  - mongodb

before_install:
  - "mongo admin --eval 'db.createUser({user: \"mlc\", pwd: \"hunter2\", roles: [{role: \"root\", db: \"admin\"}]})'"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.4-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

after_success: npx jest --coverage && npx codecov
